# Generated by Django 5.2 on 2025-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produccion_G6', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Proyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='Empleado',
            new_name='empleado',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='Proyecto',
            new_name='proyecto',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='En proceso'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='notas',
            field=models.TextField(default='Notas de la tarea'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja'),
        ),
    ]
