# Generated by Django 5.2 on 2025-04-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produccion_G6', '0002_rename_proyecto_cliente_proyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='notas',
            field=models.TextField(default='Notas del empleado'),
        ),
    ]
