# Generated by Django 5.2 on 2025-05-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produccion_G6', '0002_alter_proyecto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_empleado', to='gestion_produccion_G6.empleado'),
        ),
    ]
