# Generated by Django 5.2 on 2025-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produccion_G6', '0003_alter_tarea_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='responsables',
            field=models.ManyToManyField(blank=True, related_name='proyectos_responsables', to='gestion_produccion_G6.empleado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Asignado', 'Asignado'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='Abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Baja', max_length=20),
        ),
    ]
